title: Kaifeng Yan | AI Engineering Portfolio
page-top-title: Kaifeng Yan
top-section-bg-text: AI Engineering Portfolio
home-subtitle: Kaifeng Yan&ensp;|&ensp;严凯丰
copyright-text: '&copy; Kaifeng Yan 2024-2026. All Rights Reserved.'
