title: Kaifeng Yan's Homepage
page-top-title: Kaifeng Yan
top-section-bg-text: Computer Science
home-subtitle: Kaifeng Yan&ensp;|&ensp;严凯丰
copyright-text: '&copy; Kaifeng Yan 2024-2025. All Rights Reserved.'
